# Generated by Django 5.2 on 2025-08-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_customer_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='picture',
            field=models.URLField(default='https://cwdaust.com.au/wpress/wp-content/uploads/2015/04/placeholder-restaurant.png', max_length=10000),
        ),
    ]
